# Generated by Django 5.0.6 on 2024-05-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OutfitGeneratorAPI', '0003_remove_outfit_code_remove_piece_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='style',
            field=models.CharField(choices=[('CS', 'Casual'), ('FM', 'Formal'), ('SP', 'Sport'), ('BS', 'Business')], default=None, max_length=100),
        ),
    ]
