# Generated by Django 5.0.6 on 2024-05-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OutfitGeneratorAPI', '0004_alter_piece_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='color',
            field=models.CharField(choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('YELLOW', 'Yellow'), ('BLACK', 'Black'), ('WHITE', 'White'), ('ORANGE', 'Orange'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('BROWN', 'Brown'), ('GRAY', 'Gray')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='style',
            field=models.CharField(choices=[('CASUAL', 'Casual'), ('FORMAL', 'Formal'), ('SPORT', 'Sport'), ('BUSINESS', 'Business')], max_length=100, null=True),
        ),
    ]
