# Generated by Django 5.0.6 on 2024-05-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OutfitGeneratorAPI', '0005_piece_color_alter_piece_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='user',
            new_name='username',
        ),
    ]
