# Generated by Django 5.0.6 on 2024-05-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OutfitGeneratorAPI', '0006_rename_user_outfit_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
